name: Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: test
      DOCKER_IMAGE_TAG: latest
      SCRIPT_PATH: /application/run-unit-tests.sh
      DOCKER_FILE_LOC: docker/Dockerfile-test

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} -f ${{  env.DOCKER_FILE_LOC }} .

      - name: Run Docker Container and Execute Script
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} ${{ env.SCRIPT_PATH }}
